spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/marketplace?serverTimezone=GMT"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: "{SPRING_DATASOURCE_USERNAME}: root"
    password: "{SPRING_DATASOURCE_PASSWORD}: root"

  # For endpoints matching in Swagger
  mvc.pathmatch.matching-strategy: "ANT_PATH_MATCHER"